version: "3.8"

services:
frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 80:3000

  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    volumes:
      - mysql_panjpar:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=panjpardbpasswordroot
      - MYSQL_DATABASE=flashcard
      - MYSQL_USER=panjparuser
      - MYSQL_PASSWORD=panjpardbpassword
    ports:
      - "3306:3306"

  backend:
    depends_on: 
      mysql:
        condition: service_started
    build: ./backend
    ports:
      - 8000:80

    entrypoint: ./docker-entrypoint.sh
    user: ${CURRENT_UID}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: panjpardbpasswordroot

volumes:
  mysql_panjpar: